apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

resources:
  - storagesystem.yaml
  - storagecluster.yaml

vars:
- fieldref:
    fieldPath: metadata.name
  name: NAMESPACE
  objref:
    apiVersion: v1
    kind: Namespace
    name: openshift-storage

