apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  manageNodes: false
  monDataDirHostPath: /var/lib/rook
  storageDeviceSets:
    - name: ocs-deviceset
      count: 1
      portable: true
      replica: 3
      deviceClass: hdd
      dataPVCTemplate:
        spec:
          storageClassName: localblock   # CHANGE ME: storageclass có sẵn trên cluster
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Ti
