apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesJson6902:
- target:
    group: operators.coreos.com
    version: v1alpha1
    kind: Subscription
    name: odf-operator-subscription
  patch: |-
    - op: replace
      path: /spec/installPlanApproval
      value: Manual
