apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  name: noobaa
  namespace: openshift-storage
spec:
  cleanupPolicy:
    confirmation: delete
  image: noobaa/noobaa-core:master-20250521
  dbImage: quay.io/sclorg/postgresql-16-c9s

