apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator-subscription
  namespace: openshift-storage
spec:
  channel: alpha
  name: odf-operator
  source: odf-operator-catalog
  sourceNamespace: openshift-storage
  installPlanApproval: Automatic
  startingCSV: odf-operator.v4.19.0
